# Generated by Django 4.2 on 2023-04-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AJSK_RH', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
